# Generated by Django 2.1.4 on 2019-02-03 10:03

from django.db import migrations
import sciwagblocks.blocks
import sciwagblocks.blocks
import sciwagblocks.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_wagtail_scientific_main_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpage',
            name='body',
            field=wagtail.core.fields.StreamField(
                [
                    ('cut', wagtail.core.blocks.CharBlock(
                        classname='full subtitle', 
                        help_text='After this block the post will be cutted when displayed on the home page. On the post page this field is ignored.')
                    ), 
                    ('paragraph', wagtail.core.blocks.RichTextBlock()), 
                    ('quote', wagtail.core.blocks.StructBlock(
                        [
                            ('quote', wagtail.core.blocks.TextBlock(help_text='Quote text.', required=True, rows=3)), 
                            ('author', wagtail.core.blocks.CharBlock(help_text='Author of the quoted text.', required=False)), 
                            ('source', wagtail.core.blocks.CharBlock(help_text='Source of the quoted text.', required=False))
                        ], classname='full')
                    ), 
                    ('image', wagtail.core.blocks.StructBlock(
                        [
                            ('image', wagtail.images.blocks.ImageChooserBlock()), 
                            ('caption', sciwagblocks.blocks.MarkdownxBlock(required=False))
                        ])
                    ), 
                    ('embed', wagtail.embeds.blocks.EmbedBlock()), 
                    ('document', wagtail.documents.blocks.DocumentChooserBlock(help_text='All the text in other blocks, which is the same as document title will be replaced with the link to the document.')), 
                    ('markdown', sciwagblocks.blocks.MarkdownxBlock()), 
                    ('equation', wagtail.core.blocks.StructBlock(
                        [
                            ('equation', sciwagblocks.blocks.EquationBlock()), 
                            ('caption', sciwagblocks.blocks.MarkdownxBlock(required=False))
                        ])
                    ), 
                    ('pages', wagtail.core.blocks.PageChooserBlock()), 
                    ('columns', wagtail.core.blocks.StructBlock(
                        [
                            ('left', wagtail.core.blocks.StreamBlock(
                                [
                                    ('paragraph', wagtail.core.blocks.RichTextBlock()), 
                                    ('image', wagtail.core.blocks.StructBlock(
                                        [
                                            ('image', wagtail.images.blocks.ImageChooserBlock()), 
                                            ('caption', sciwagblocks.blocks.MarkdownxBlock(required=False))
                                        ])
                                    ), 
                                    ('markdown', sciwagblocks.blocks.MarkdownxBlock()), 
                                    ('pages', wagtail.core.blocks.PageChooserBlock())
                                ], icon='arrow-left', label='Left column content')
                            ), 
                            ('right', wagtail.core.blocks.StreamBlock(
                                [
                                    ('paragraph', wagtail.core.blocks.RichTextBlock()), 
                                    ('image', wagtail.core.blocks.StructBlock(
                                        [
                                            ('image', wagtail.images.blocks.ImageChooserBlock()), 
                                            ('caption', sciwagblocks.blocks.MarkdownxBlock(required=False))
                                        ])
                                    ), 
                                    ('markdown', sciwagblocks.blocks.MarkdownxBlock()), 
                                    ('pages', wagtail.core.blocks.PageChooserBlock())
                                ], icon='arrow-right', label='Right column content')
                            )
                        ])
                    ), 
                    ('table', wagtail.core.blocks.StructBlock(
                        [
                            ('table', sciwagblocks.blocks.table_block.ColWidthTableBlock(
                                align_classes={'htBottom': 'align-bottom', 'htCenter': 'text-center', 'htJustify': 'text-justify', 'htLeft': 'text-left', 'htMiddle': 'align-middle', 'htRight': 'text-right', 'htTop': 'align-top'}, 
                                table_options={'autoColumnSize': False, 'colHeaders': False, 'contextMenu': ['row_above', 'row_below', '---------', 'col_left', 'col_right', '---------', 'alignment', '---------', 'remove_row', 'remove_col', '---------', 'undo', 'redo'], 'editor': 'text', 'height': 108, 'minSpareRows': 0, 'renderer': 'text', 'rowHeaders': False, 'startCols': 3, 'startRows': 3, 'stretchH': 'all'}
                                )
                            ), 
                            ('caption', sciwagblocks.blocks.MarkdownxBlock(required=False))
                        ])
                    )
                ]
            ),
        ),
    ]
