# Generated by Django 2.1.4 on 2019-02-04 18:43

from django.db import migrations
import sciwagblocks.blocks.markdownx_block
import sciwagblocks.blocks.table_block
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_wagtail_scientific_main_post_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock()), ('quote', wagtail.core.blocks.StructBlock([('quote', wagtail.core.blocks.TextBlock(help_text='Quote text.', required=True, rows=3)), ('author', wagtail.core.blocks.CharBlock(help_text='Author of the quoted text.', required=False)), ('source', wagtail.core.blocks.CharBlock(help_text='Source of the quoted text.', required=False))], classname='full')), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', sciwagblocks.blocks.markdownx_block.MarkdownxBlock(required=False))])), ('embed', wagtail.embeds.blocks.EmbedBlock()), ('markdown', sciwagblocks.blocks.markdownx_block.MarkdownxBlock()), ('columns', wagtail.core.blocks.StructBlock([('left', wagtail.core.blocks.StreamBlock([('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', sciwagblocks.blocks.markdownx_block.MarkdownxBlock(required=False))])), ('markdown', sciwagblocks.blocks.markdownx_block.MarkdownxBlock()), ('pages', wagtail.core.blocks.PageChooserBlock())], icon='arrow-left', label='Left column content')), ('right', wagtail.core.blocks.StreamBlock([('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', sciwagblocks.blocks.markdownx_block.MarkdownxBlock(required=False))])), ('markdown', sciwagblocks.blocks.markdownx_block.MarkdownxBlock()), ('pages', wagtail.core.blocks.PageChooserBlock())], icon='arrow-right', label='Right column content'))])), ('pages', wagtail.core.blocks.PageChooserBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock()), ('table', wagtail.core.blocks.StructBlock([('table', sciwagblocks.blocks.table_block.ColWidthTableBlock(align_classes={'htBottom': 'align-bottom', 'htCenter': 'text-center', 'htJustify': 'text-justify', 'htLeft': 'text-left', 'htMiddle': 'align-middle', 'htRight': 'text-right', 'htTop': 'align-top'}, table_options={'autoColumnSize': False, 'colHeaders': False, 'contextMenu': ['row_above', 'row_below', '---------', 'col_left', 'col_right', '---------', 'alignment', '---------', 'remove_row', 'remove_col', '---------', 'undo', 'redo'], 'editor': 'text', 'height': 108, 'minSpareRows': 0, 'renderer': 'text', 'rowHeaders': False, 'startCols': 3, 'startRows': 3, 'stretchH': 'all'})), ('caption', sciwagblocks.blocks.markdownx_block.MarkdownxBlock(required=False))]))]),
        ),
    ]
