# Generated by Django 3.1.3 on 2020-11-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201121_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='generate_table_numbers',
            field=models.BooleanField(default=False, help_text='Indicates if  table numbers (such as Table 1) should be geberated for Table block when rendering post.', verbose_name='Generate table numbers'),
        ),
        migrations.AlterField(
            model_name='postpage',
            name='generate_equation_numbers',
            field=models.BooleanField(default=False, help_text='Indicates if equation numbers (such as (1)) should be added on the right side of the Equation block when rendering post.', verbose_name='Generate equation numbers'),
        ),
        migrations.AlterField(
            model_name='postpage',
            name='generate_figure_numbers',
            field=models.BooleanField(default=False, help_text='Indcates if figure numbers (such as Figure 1) should be generated for Figure block when rendring post.', verbose_name='Generate figure numbers'),
        ),
    ]
